dev:
 enabled: true
drill:
 title: "&b&lDiamond Drill"
 lore:
  - "&bDiamond Drill"
  - "&fDig down to dig a large area"
  - "&f&o3x3 area of effect"
hoe:
 title: "&b&lIndustrial Hoe"
 lore:
  - "&bIndustrial Hoe"
  - "&fHoe dirt to hoe a large area"
  - "&f&o3x3 area of effect"
